name: DevExtreme Vue Tests

on:
  pull_request:
  push:
    branches: [23_2]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Install npm packages
      run: npm i --no-audit --no-fund

#    - name: Run lint
#      run: npm run lint

    - name: Build devextreme-vue-generator
      working-directory: node_modules/devextreme-vue-generator
      run: |
        npm i --no-audit --no-fund
        npm run build:local

#    - name: Pack DevExtreme
#      working-directory: devextreme/packages/devextreme/artifacts/npm/devextreme
#      run: |
#        npm pack
#        mv devextreme*.tgz devextreme.tgz
#
#    - name: Install devextreme package
#      run: |
#        npm i --save-dev ./devextreme/packages/devextreme/artifacts/npm/devextreme/devextreme.tgz --workspace=devextreme-vue --workspace=devextreme-vue2-strategy --no-audit --no-fund

    - name: Generate metadata
      working-directory: packages/devextreme
      run: npm run discover-declarations

    - name: Generate wrappers
      run: npx dx-tools integration-data-generator --js-scripts packages/devextreme/js --artifacts packages/devextreme/artifacts/internal-tools --output-path packages/devextreme-vue/metadata/integration-data.json

    - name: Check generated code
      shell: bash
      run: |
        git add . -N
        changes=$(git diff HEAD -- packages/devextreme-vue/src packages/vue2-strategy/src)
        if [ -n "$changes" ]; then
          echo "Generated code is outdated. The following files have uncommitted changes:"
          echo "$changes";
          echo "To update generated code, generate metadata, build packages and commit changes."
          exit 1
        fi

    - name: Archive internal-tools artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: internal-tools-artifacts
        path: packages/devextreme/artifacts/internal-tools/
        retention-days: 7

    - name: Build packages
      run: |
        npx nx build devextreme-main
        npx nx build devextreme-vue

    - name: Run tests with Vue
      working-directory: packages/devextreme-vue
      run: npm run test

    - name: Check packing
      run: npx nx run-many -t pack -p devextreme-vue devextreme-vue2-strategy

